on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - .git*
      - '**.md'
      - 'library.properties'
      - 'library.json'
  pull_request:
    branches:
      - main
      - develop
    paths-ignore:
      - .git*
      - '**.md'
      - 'library.properties'
      - 'library.json'

jobs:
  build:
    name: 'Build Test: ${{matrix.board.arch}}:${{matrix.board.name}}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board:
          - vendor: arduino
            arch: avr
            name: uno
          - vendor: arduino
            arch: megaavr
            name: uno2018
        include:
          - index: https://downloads.arduino.cc/packages/package_index.json
            board:
              vendor: arduino
    steps:
      - uses: actions/checkout@v4
      - name: compile example sketchs
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{matrix.board.vendor}}:${{matrix.board.arch}}:${{matrix.board.name}}
          platforms: |
            - name: ${{matrix.board.vendor}}:${{matrix.board.arch}}
              source-url: ${{matrix.index}}
          sketch-paths: |
            - examples
          libraries: |
            - source-path: ./
          verbose: true
